### ISSUE TITLE
Test using VLAN interfaces

### ISSUE THREAD

**Issue by drsound** [drsound/fault_tolerant_router#3]
Test using VLAN interfaces: Fault Tolerant Router has always been used with physical interfaces, each uplink on it's own physical interface.

**Comment by 8none1** [comment]
Hi there!  I'm using a Raspberry Pi with both a PPPoE uplink (on ppp1) and some VLANs (eth0, eth0.10, eth0.20, etc).  I'm having problems with getting the routing to work reliably.  But, I think that's partly because the VDSL routers provided by my ISPs are junk.

Let me know what I can do to help.

I'm willcooke on Freenode.

Cheers!

**Comment by drsound** [comment]
How is it going with your VLANs? Does fault_tolerant_router work with them?

**Comment by 8none1** [comment]
Yeah, it worked fine.  As far as FTR is concerned it's just another
interface it seems.

**Comment by drsound** [comment]
Great news, thanks!
